/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#38485d',
        'tertiary-fixed': '#dae2fd',
        error: '#ba1a1a',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed': '#d3e4fe',
        'on-surface-variant': '#45474c',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'surface-tint': '#545f73',
        'surface-container': '#eceef0',
        primary: '#091426',
        'surface-dim': '#d8dadc',
        outline: '#75777d',
        'on-secondary-fixed': '#0b1c30',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-container': '#888fa7',
        'surface-bright': '#f7f9fb',
        'primary-container': '#1e293b',
        background: '#f7f9fb',
        'on-tertiary-fixed-variant': '#3f465c',
        'inverse-surface': '#2d3133',
        'tertiary-fixed-dim': '#bec6e0',
        'tertiary-container': '#20283c',
        'on-tertiary-fixed': '#131b2e',
        'error-container': '#ffdad6',
        'secondary-container': '#d0e1fb',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#bcc7de',
        secondary: '#505f76',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#d8e3fb',
        'on-secondary-container': '#54647a',
        'on-error': '#ffffff',
        surface: '#f7f9fb',
        'on-background': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'secondary-fixed-dim': '#b7c8e1',
        'on-primary-fixed': '#111c2d',
        tertiary: '#0b1426',
        'on-primary-fixed-variant': '#3c475a',
        'on-secondary': '#ffffff',
        'on-primary-container': '#8590a6',
        'outline-variant': '#c5c6cd',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'inverse-primary': '#bcc7de',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        'margin-mobile': '20px',
        'margin-desktop': '80px',
        'content-gap': '32px',
        gutter: '24px',
        base: '8px',
      },
      fontFamily: {
        'headline-xl': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': [
          '48px',
          {
            lineHeight: '1.1',
            letterSpacing: '0',
            fontWeight: '600',
          },
        ],
        'headline-lg-mobile': [
          '28px',
          {
            lineHeight: '1.2',
            letterSpacing: '0',
            fontWeight: '600',
          },
        ],
        'body-md': [
          '16px',
          {
            lineHeight: '1.5',
            fontWeight: '400',
          },
        ],
        'headline-lg': [
          '32px',
          {
            lineHeight: '1.2',
            letterSpacing: '0',
            fontWeight: '600',
          },
        ],
        'label-sm': [
          '12px',
          {
            lineHeight: '1.4',
            fontWeight: '500',
          },
        ],
        'label-md': [
          '14px',
          {
            lineHeight: '1.4',
            letterSpacing: '0',
            fontWeight: '500',
          },
        ],
        'body-lg': [
          '18px',
          {
            lineHeight: '1.6',
            fontWeight: '400',
          },
        ],
      },
    },
  },
  plugins: [],
};
